-- Schema for Shomed Remedies MIS, Project 1: data migration.
-- Two tables: data_raw (text staging) and data (typed canonical), plus
-- five indexes covering the hot filter combos in src/reports/*.ts and
-- src/lib/schema.ts::parseFilters. pg_trgm is enabled day 1 so Project 2
-- can fuzzy-match brands/HQs/doctors without a separate migration.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ──────────────────────────────────────────────────────────────────────────
-- data_raw — COPY landing zone. All 75 columns as text so malformed rows
-- (non-numeric values in numeric columns) don't abort the entire batch.
-- TRUNCATE'd at the start and end of every ingest; effectively 0 bytes
-- at rest.
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS data_raw (
  pts        text,
  pp         text,
  co         text,
  fy         text,
  zbm        text,
  abm        text,
  tbm        text,
  hq_new     text,
  hq         text,
  customer_n text,
  yyyymm     text,
  year       text,
  qtr        text,
  hly        text,
  mth        text,
  month      text,
  seg        text,
  item_code  text,
  item_name  text,
  opening_qt text,
  opening_va text,
  net_sales_ text,
  sales_qty_ text,
  sales_valu text,
  sales_qty2 text,
  foc_qty__s text,
  foc_value_ text,
  sales_qty3 text,
  sales_val2 text,
  closing_qt text,
  closing_va text,
  tgt_qty_p  text,
  tgt_val_p  text,
  tgt_qty_s  text,
  tgt_val_s  text,
  cn_qty     text,
  cn_value   text,
  doc_code   text,
  dr_name    text,
  no_patient text,
  dc_patient text,
  pap_stn    text,
  pap_date   text,
  done_by    text,
  exp_dt     text,
  camp_exp   text,
  sample_qty text,
  sample_exp text,
  sample_pts text,
  mrkt_qty   text,
  mrkt_exp   text,
  mrkt_pts   text,
  coll       text,
  coll_date  text,
  category   text,
  gri_qty    text,
  gri_sales  text,
  rdsi_qty   text,
  rdsi_sales text,
  sale_qty   text,
  sale_sales text,
  net_qty    text,
  net_sales  text,
  foc_rate   text,
  foc_value  text,
  foc_val_n  text,
  batch_no_  text,
  expiry_dat text,
  return_qty text,
  return_amt text,
  expired    text,
  near_3     text,
  near_6     text,
  near_9     text,
  remark     text
);

-- ──────────────────────────────────────────────────────────────────────────
-- data — canonical typed table. Numeric columns mirror the existing
-- DuckDB DOUBLE choices; text columns mirror VARCHAR. yyyymm stays text
-- to preserve leading zeros. Date-like columns stay text because the CSV
-- uses '/  /' as an empty-date sentinel.
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS data (
  id         bigserial PRIMARY KEY,
  pts        numeric(14,2),
  pp         numeric(14,2),
  co         text,
  fy         text,
  zbm        text,
  abm        text,
  tbm        text,
  hq_new     text,
  hq         text,
  customer_n text,
  yyyymm     text,
  year       numeric(14,2),
  qtr        text,
  hly        text,
  mth        numeric(14,2),
  month      text,
  seg        text,
  item_code  text,
  item_name  text,
  opening_qt numeric(14,2),
  opening_va numeric(14,2),
  net_sales_ numeric(14,2),
  sales_qty_ numeric(14,2),
  sales_valu numeric(14,2),
  sales_qty2 numeric(14,2),
  foc_qty__s numeric(14,2),
  foc_value_ numeric(14,2),
  sales_qty3 numeric(14,2),
  sales_val2 numeric(14,2),
  closing_qt numeric(14,2),
  closing_va numeric(14,2),
  tgt_qty_p  numeric(14,2),
  tgt_val_p  numeric(14,2),
  tgt_qty_s  numeric(14,2),
  tgt_val_s  numeric(14,2),
  cn_qty     numeric(14,2),
  cn_value   numeric(14,2),
  doc_code   text,
  dr_name    text,
  no_patient numeric(14,2),
  dc_patient numeric(14,2),
  pap_stn    text,
  pap_date   text,
  done_by    text,
  exp_dt     text,
  camp_exp   numeric(14,2),
  sample_qty numeric(14,2),
  sample_exp numeric(14,2),
  sample_pts numeric(14,2),
  mrkt_qty   numeric(14,2),
  mrkt_exp   numeric(14,2),
  mrkt_pts   numeric(14,2),
  coll       numeric(14,2),
  coll_date  text,
  category   text,
  gri_qty    numeric(14,2),
  gri_sales  numeric(14,2),
  rdsi_qty   numeric(14,2),
  rdsi_sales numeric(14,2),
  sale_qty   numeric(14,2),
  sale_sales numeric(14,2),
  net_qty    numeric(14,2),
  net_sales  numeric(14,2),
  foc_rate   numeric(14,2),
  foc_value  numeric(14,2),
  foc_val_n  numeric(14,2),
  batch_no_  text,
  expiry_dat text,
  return_qty numeric(14,2),
  return_amt numeric(14,2),
  expired    numeric(14,2),
  near_3     numeric(14,2),
  near_6     numeric(14,2),
  near_9     numeric(14,2),
  remark     text
);

CREATE INDEX IF NOT EXISTS idx_data_fy_period ON data (fy, yyyymm);
CREATE INDEX IF NOT EXISTS idx_data_hq        ON data (hq_new);
CREATE INDEX IF NOT EXISTS idx_data_seg       ON data (seg);
CREATE INDEX IF NOT EXISTS idx_data_item      ON data (item_name);
CREATE INDEX IF NOT EXISTS idx_data_zbm_abm   ON data (zbm, abm);
